[versions]
tangemBlockchainSdk = "develop-1005"
#tangemBlockchainSdk = "0.0.1" # Keep it! - used for local builds
tangemCardSdk = "develop-451"
#tangemCardSdk = "0.0.1" # Keep it! - used for local builds ^
tangemVico = "2.0.0-alpha.25-tangem-developments8"
#tangemVico = "0.0.1" # Keep it! - used for local builds ^



[libraries]
blockchain = { module = "com.tangem:blockchain", version.ref = "tangemBlockchainSdk" }
card-android = { module = "com.tangem.tangem-sdk-kotlin:android", version.ref = "tangemCardSdk" }
card-core = { module = "com.tangem.tangem-sdk-kotlin:core", version.ref = "tangemCardSdk" }

vico-compose = { group = "com.tangem.vico", name = "compose", version.ref = "tangemVico" }
vico-compose-m3 = { group = "com.tangem.vico", name = "compose-m3", version.ref = "tangemVico" }
vico-core = { group = "com.tangem.vico", name = "core", version.ref = "tangemVico" }